### ISSUE TITLE
A few files for ir remote control

### ISSUE THREAD

**Issue by knedlyk** [warpme/archlinuxarm#1]
Please add the following package: eventlircd with the following file:
/usr/lib/systemd/system/eventlircd.service
```
[Unit]
Description=Eventlirc server daemon

[Service]
ExecStart=/usr/sbin/eventlircd -f --evmap=/etc/eventlircd.d --socket=/run/lirc/lircd
KillMode=process
TimeoutStopSec=1s

[Install]
WantedBy=multi-user.target
```
Please also add a script which will load the following line:
/usr/bin/ir-keytable -c -w /usr/lib/udev/rc_keymaps/tanix_tx5max.toml
It will load the correct keymap for the ir remote control.

**Comment by warpme** [comment]
Well - my intention to offer packed SD card images of archlinuxarm - just for rpi4/tx6 - was to help mythtv developers quickly start with native aarch64 build/test environment. In this context - i assume any mods to public vanilla archlinux rootfs in those images (like your's request) should be rather done at post flash/fs expand/full update os system.
