### ISSUE TITLE
Is it possible to build armhf version for the TX6 board?

### ISSUE THREAD

**Issue by knedlyk** [warpme/archlinuxarm#2]
Just curious. The reason is very simple: it is not possible to view NetFlix and Amazon with Kodi on aarch64, there is no  widevine version for the aarch64 platform. That is why it would be great to have armhf version as well.

**Comment by warpme** [comment]
Well - my intention to offer packed SD card images of archlinuxarm - just for rpi4/tx6 - was to help mythtv developers quickly start with native aarch64 build/test environment. In this context - i don't have plans to offer such packed images for other boards nor architectures
You Q however lead me to idea of new project: MiniArch (set of archlinuxarm SD card images for all board i'm supporting in MiniMyth2: https://github.com/warpme/minimyth2#general-functionality )

**Comment by warpme** [comment]
Hi  - per my las comment : https://github.com/warpme/miniarch
May you give try?

ps: by some reason installing endeavour os fails....
